### PR TITLE
Change the default behavior for arrays from merging to overwriting

### LINKED ISSUE #12: Option overwriting doesn't work (for me, at least)
Hiya, 

I'm using an optional YML file with additional options as well as changes to the existing ones, which is loaded if it exists (doing so via `Settings.add_source!("#{Rails.root}/config/lpl.yml")` in my app's initializer). The problem is that I have the following defined in settings.yml:

    lpl: 
      ..
      language_options:
        - de
        - en
      ..

while my own file has

    lpl: 
      ..
      language_options:
        - de
      ..

I was expecting the result to be that `Settings.lpl.language_options` would hold `["de"]`, yet it still holds `["de", "en"]`. Do I need to do anything besides 

    if File.exists?("#{Rails.root}/config/lpl.yml")
      Settings.add_source!("#{Rails.root}/config/lpl.yml")
      Settings.reload!
    end

when loading the additional settings in my initlializer? Or should I be unloading all settings and include all the settings in `lpl.yml`, not just the ones that would add to/overwrite stuff from `config.yml`? And if so—how? 

Thanks! :)

### PR DESCRIPTION
**Pull request by hnakamur**
Hi, this is a pull request to fix #12.
Could you review this?
Thanks!

### CODE REVIEW

**Comment by vinceve** [comment]
+1 This looks good!

**Comment by vinceve** [comment]
I tested it in our project. It doesn't work entirely. I noticed that my environment specific settings are overridden by the settings.yml. Normally it should work in the opposite way.

**Comment by hnakamur** [comment]
@vinceve Thanks for testing. Could you share minimal settings.yml and settings.local.yml to reproduce problems?

**Comment by vinceve** [comment]
My config:

settings.yml:
```yaml
service:
  hosts:
    - 'test'
```

settings/development.local.yml:
```yaml
service:
  hosts:
    - 'development'
```

if you do Settings.service.hosts:
=> [
  [0] "test"
]

**Comment by hnakamur** [comment]
@vinceve I added more test cases and fixed merging with overwrite_arrays.
Could you try again?
Thanks.

**Comment by vinceve** [comment]
@hnakamur I had sent you a merge request for your branch :-) Where I fixed it already yesterday. I'll check if it's the same.

**Comment by hnakamur** [comment]
Sorry, I hadn't notice your pull request. My fix seems the same as yours.

**Comment by fredwu** [comment]
Hi guys, great conversations!

As I commented in PR #103:

> Implementation wise, PR #110 has just been merged in - we now use the gem version of deep_merge, is this still achievable without changing deep_merge's source code?

**Comment by pkuczynski** [comment]
Fixed in #137 although by default it does not overwrite, to maintain backward compatibility

**Pull request closed without merging**
