### PR TITLE
Config doesn't have to be a Rails Engine

### PR DESCRIPTION
**Pull request by amatsuda**
I found that Config defines an isolated Engine class under Rails environment, but this simple plugin actually does not use Rails Engine feature at all. This plugin already has a Railtie, and that's enough for doing things that this plugin offers.

Creating an unused Engine class like this is not just unnecessary but indeed rather harmful for the users' applications, because it slows down the application initialization process, consumes much memory, and slows down auto/eager loading, request handling, rendering, etc. by adding entries for them.

### CODE REVIEW

**Comment by pkuczynski** [comment]
@amatsuda thank you for your contribution. Could you please add CHANGELOG entry?

@pyromaniac @rdubya @supremebeing7 what you think about this PR?

**Comment by amatsuda** [comment]
@pkuczynski 
> Could you please add CHANGELOG entry?

Done!

**Comment by pkuczynski** [comment]
Thanks! Sorry for such a long time for merging this one...

**Comment by pkuczynski** [comment]
Will be released soon with 2.2.0

**Pull request merged**
