### PR TITLE
Add overwrite_arrays option

### PR DESCRIPTION
**Pull request by Fryguy**
This is an extraction from
https://github.com/railsconfig/config/pull/103 where @dtaniwaki had
added this option, but had done it prior to the deep_merge extraction.

This depends on https://github.com/danielsdeleo/deep_merge/pull/21

Paired with @carbonin <https://github.com/carbonin> on this.

### CODE REVIEW

**Comment by Fryguy** [comment]
This will fail Travis until danielsdeleo/deep_merge#21 is merged and the gemspec is updated here.

**Comment by Fryguy** [comment]
@pkuczynski @fredwu Not sure who to ping on this, so hoping I pick the right people :pray: Do you also do reviews / merge on https://github.com/danielsdeleo/deep_merge ?

**Comment by fredwu** [comment]
@Fryguy No I don't believe any of us do - in fact by the looks of it `deep_merge` hasn't seen any commits since January 2014 so it's not actively maintained any more...

**Comment by Fryguy** [comment]
I've updated my PR on deep_merge...hopefully it will pass now...then I'll see if I can get a new deep_merge version released

**Comment by pkuczynski** [comment]
@Fryguy it seems that you have some conflicts. Could you please rebase on top of current master and squash your commits into one?

I got a message from @danielsdeleo and he will look at the deep_merge PR in June...

**Comment by Fryguy** [comment]
My deep_merge PR was merged...just need a release of deep_merge itself.

**Comment by pkuczynski** [comment]
When do you think it will be released?

**Comment by kapso** [comment]
+1

**Comment by vinceve** [comment]
@all I submitted a new pull request where I pushed the same gem under a new name (deep_merge2). The latest release of the deep_merge gem was in 2011, so I guess it wasn't going to be released soon.

**Comment by Fryguy** [comment]
@pkuczynski I'll rebase this today...I'll also see if I can  @danielsdeleo to release a new deep_merge

**Comment by Fryguy** [comment]
@pkuczynski I just got release rights on the deep_merge gem.  Expect a new version soon and then I will update this PR with the new gem.

**Comment by Fryguy** [comment]
@pkuczynski I released a new version of the deep_merge gem and updated this PR accordingly.

**Comment by kbrock** [comment]
Cool stuff. Any objections before merging?

**Comment by Fryguy** [comment]
@pkuczynski @fredwu Bump?

Incidentally, we've been using this branch in ManageIQ / CloudForms for quite a while now, and all seems well!

**Comment by pkuczynski** [comment]
I am on holiday at the moment. Can have a look when I am back

**Comment by Fryguy** [comment]
@pkuczynski Sounds great!  Enjoy your holiday! 😎

**Comment by pkuczynski** [comment]
The only thing I will change is to make it default to 'true', as this should be the correct behaviour from the start I believe. I will also add a note in the documentation, to highlight this change.

**Comment by Fryguy** [comment]
🎉 Thanks @pkuczynski

**Pull request merged**
