### PR TITLE
Add method prepend_source!

### PR DESCRIPTION
**Pull request by eugenk**
Sometimes you want to have custom configuration files that are loaded
before the default files, in order to let the `*.local.*` files
overwrite those settings. This method enables this behaviour.

### CODE REVIEW

**Comment by fredwu** [comment]
That's a great addition @eugenk! :+1: Could you please add some tests and add the usage to the README? I'm happy to merge this once tests and README are updated. :)

**Comment by eugenk** [comment]
Sure. I just rebased on master and added the specs and usage.

**Comment by eugenk** [comment]
The specs fail with ruby 1.9.3, but I can't imagine how the failed specs are linked to the new code of this pull request.

**Comment by fredwu** [comment]
Nice work!

**Pull request merged**
