### PR TITLE
Restrict constant search to Kernel only (#189)

### LINKED ISSUE #189: NameError for Kernel::Settings when the global const Settings is already defined.
This bug occurs in line 55 of lib/config.rb when the constant `Settings` is already defined, but somehow Kernel::Settings is not. I am not 100% clear on how to achieve this scenario. The culprit in my setup seems to be the configliere gem which is loaded by a dependency of my project.

The specific issue is that `const_defined?` has default behavior (`inherit=true`) that also searches Object.

### PR DESCRIPTION
**Pull request by malakai97**
This fixes #189 while retaining the warning suppression behavior.

### CODE REVIEW

**Comment by pkuczynski** [comment]
Looks good! Could you also provide test covering this issue?

**Comment by malakai97** [comment]
Most likely yes, but I'm not sure when I'll get to that.

**Comment by malakai97** [comment]
I can also fix the code climate line size issue by converting it to a standard if block, or we can leave it.

**Comment by pkuczynski** [comment]
CodeClimate is easy to fix. I am more interested in a unit test covering this case. I hope you can work on this soon...

**Comment by pkuczynski** [comment]
Any luck with adding some tests @malakai97?

**Comment by malakai97** [comment]
I have created a test in `spec/const_loading_spec.rb`.  The reason I placed it here instead of just in `config_spec.rb` is that it passes without the fix if `spec_helper` has been loaded. I don't know why.

Thus, you can see the failure and subsequent pass via:

`bundle exec rspec spec/const_loading_spec.rb`

**Comment by malakai97** [comment]
Possible strategies for getting it to fail when running the entire suite:

1. Figure out what spec_helper is doing that "fixes" it, and undo it in the test itself.
2. Don't include spec_helper by default, and instead require it in the spec files that need it.

I expect you don't want to do number two.

**Comment by pkuczynski** [comment]
Indeed, number one is better :) I guess u would have to figure out how to emulate the scenario when the constant Settings is already defined, but somehow Kernel::Settings is not. Otherwise we can't be sure that propose change is doing what it should be.

**Pull request closed without merging**
