### PR TITLE
Use sprockets 3.x for Rails 4.2

### PR DESCRIPTION
**Pull request by qnighy**
To fix CI errors in #255.

### CODE REVIEW

**Comment by jcoyne** [comment]
Committers, please merge this or #262, so we can continue to work on other issues without having to deal with a broken build.

**Comment by qnighy** [comment]
cc: @pkuczynski or someone for merging #251, #254, #256 or #262

**Comment by pkuczynski** [comment]
I will have a look tomorrow when I am back home.

**Comment by qnighy** [comment]
Still unable to merge by myself

image

**Comment by pkuczynski** [comment]
Merged! Sorry for the delay...

**Pull request merged**
